// ==============================================================================
// RELIEFGRID AI — Synthetic Demo Data Specification
// Compliant with 01_RELIEFGRID_PRODUCT.md & 03_RELIEFGRID_SUPABASE.md
// Realistic Pakistan-inspired locations: Lahore, Karachi, Islamabad, Rawalpindi, Multan
// Clearly labeled: SYNTHETIC DEMO DATA — NOT A LIVE EMERGENCY SERVICE
// ==============================================================================

import {
  Incident,
  Resource,
  Hospital,
  Shelter,
  ReliefHub,
  ReliefItem,
  Volunteer,
  SafetyAlert,
  AIRecommendation,
  EmergencyZone,
} from '../types';

export const INITIAL_ZONES: EmergencyZone[] = [
  { id: 'zone-1', name: 'Zone 4 — Ravi Basin Floodway', city: 'Lahore', risk_level: 'critical', population_estimate: 85000, synthetic_demo: true, active_incidents_count: 7 },
  { id: 'zone-2', name: 'Lyari Coastal Sector 2', city: 'Karachi', risk_level: 'high', population_estimate: 140000, synthetic_demo: true, active_incidents_count: 5 },
  { id: 'zone-3', name: 'Margalla Foothills Sector E-11', city: 'Islamabad', risk_level: 'moderate', population_estimate: 42000, synthetic_demo: true, active_incidents_count: 3 },
  { id: 'zone-4', name: 'Nullah Lai Corridor', city: 'Rawalpindi', risk_level: 'critical', population_estimate: 110000, synthetic_demo: true, active_incidents_count: 6 },
  { id: 'zone-5', name: 'Chenab Flood Embankment', city: 'Multan', risk_level: 'high', population_estimate: 65000, synthetic_demo: true, active_incidents_count: 4 },
];

// Primary signature demo incident: 18 people trapped in flooded neighborhood
export const PRIMARY_DEMO_INCIDENT: Incident = {
  id: 'inc-demo-primary',
  incident_code: 'RG-1042',
  reporter_id: 'user-citizen-1',
  reporter_name: 'Tariq Mehmood',
  reporter_phone: '+92 300 5551042',
  incident_type: 'flood',
  title: '18 People Trapped in Rapidly Flooding Residential Street',
  description: '18 people are trapped in a flooded neighborhood. Two elderly people and one infant need assistance. Water level rising above 4.5 feet. Medical support may be required immediately.',
  location_text: 'Street 7, Sector B, Shahdara Town near Ravi Riverbank',
  city: 'Lahore',
  latitude: 31.6210,
  longitude: 74.2825,
  affected_people_count: 18,
  priority: 'critical',
  priority_score: 96,
  status: 'awaiting_approval',
  verification_status: 'verified',
  immediate_danger: true,
  medical_need: true,
  synthetic_demo: true,
  vulnerabilities: {
    infants_count: 1,
    children_count: 3,
    elderly_count: 2,
    disabled_count: 1,
    pregnant_count: 0,
    critical_medical_count: 1,
    notes: 'Elderly diabetic female requiring oxygen assistance, 7-month infant in cold water exposure risk.'
  },
  created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  updated_at: new Date().toISOString(),
};

// 25+ realistic incidents across Pakistan
export const INITIAL_INCIDENTS: Incident[] = [
  PRIMARY_DEMO_INCIDENT,
  {
    id: 'inc-1043',
    incident_code: 'RG-1043',
    reporter_name: 'Fatima Zahra',
    incident_type: 'building_collapse',
    title: 'Partial Roof Collapse at 3-Story Commercial Plaza',
    description: 'Ground floor structural column yielded following heavy downpour. 8 people trapped inside store.',
    location_text: 'Bismillah Chowk, Saddar Bazaar',
    city: 'Rawalpindi',
    latitude: 33.5973,
    longitude: 73.0479,
    affected_people_count: 8,
    priority: 'critical',
    priority_score: 92,
    status: 'dispatched',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    assigned_resource_id: 'res-usar-1',
    assigned_resource_name: 'Heavy USAR Unit H-01',
    vulnerabilities: { infants_count: 0, children_count: 1, elderly_count: 2, disabled_count: 0, pregnant_count: 0, critical_medical_count: 2 },
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1044',
    incident_code: 'RG-1044',
    reporter_name: 'Bilal Khan',
    incident_type: 'flood',
    title: 'Flash Flood Cutoff in Low-Lying Settlement',
    description: 'Nullah Lai water overflowed boundary wall. 12 residents stranded on rooftop.',
    location_text: 'Dhok Ratta, near Railway Bridge',
    city: 'Rawalpindi',
    latitude: 33.6050,
    longitude: 73.0550,
    affected_people_count: 12,
    priority: 'critical',
    priority_score: 89,
    status: 'en_route',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: false,
    synthetic_demo: true,
    assigned_resource_id: 'res-boat-2',
    assigned_resource_name: 'Zodiac Rescue Boat B-02',
    vulnerabilities: { infants_count: 1, children_count: 4, elderly_count: 1, disabled_count: 0, pregnant_count: 1, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1045',
    incident_code: 'RG-1045',
    reporter_name: 'Dr. Kamran Qureshi',
    incident_type: 'heatwave',
    title: 'Severe Heat Exhaustion Cluster at Transit Terminal',
    description: '14 commuters collapsed due to 46°C temperature with high humidity. Need mobile cooling & IV fluids.',
    location_text: 'Tower Bus Interchange, I.I. Chundrigar Road',
    city: 'Karachi',
    latitude: 24.8508,
    longitude: 67.0011,
    affected_people_count: 14,
    priority: 'high',
    priority_score: 82,
    status: 'on_scene',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    assigned_resource_id: 'res-amb-3',
    assigned_resource_name: 'Advanced Life Support Ambulance ALS-03',
    vulnerabilities: { infants_count: 0, children_count: 0, elderly_count: 4, disabled_count: 1, pregnant_count: 0, critical_medical_count: 3 },
    created_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1046',
    incident_code: 'RG-1046',
    reporter_name: 'Zainab Bibi',
    incident_type: 'fire',
    title: 'Warehouse Fire Spreading to Adjacent Residential Units',
    description: 'Chemical packaging warehouse ablaze. Thick toxic smoke entering adjoining 4 houses.',
    location_text: 'Site Industrial Area, Metroville',
    city: 'Karachi',
    latitude: 24.9125,
    longitude: 66.9950,
    affected_people_count: 22,
    priority: 'critical',
    priority_score: 94,
    status: 'dispatched',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    assigned_resource_id: 'res-fire-1',
    assigned_resource_name: 'HazMat & Foam Tender F-01',
    vulnerabilities: { infants_count: 2, children_count: 6, elderly_count: 3, disabled_count: 0, pregnant_count: 1, critical_medical_count: 2 },
    created_at: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1047',
    incident_code: 'RG-1047',
    reporter_name: 'Usman Ali',
    incident_type: 'water_shortage',
    title: 'Drinking Water Contamination Following Pipeline Rupture',
    description: 'Main municipal line flooded with runoff. Over 150 families lack potable water for 24h.',
    location_text: 'Mochipura, Old City',
    city: 'Multan',
    latitude: 30.1984,
    longitude: 71.4687,
    affected_people_count: 150,
    priority: 'high',
    priority_score: 78,
    status: 'response_planning',
    verification_status: 'verified',
    immediate_danger: false,
    medical_need: false,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 12, children_count: 35, elderly_count: 20, disabled_count: 5, pregnant_count: 4, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1048',
    incident_code: 'RG-1048',
    reporter_name: 'Suleman Dar',
    incident_type: 'storm',
    title: 'High-Tension Power Cable Down on Waterlogged Street',
    description: 'Severe thunderstorm snapped overhead electricity lines into standing water. Road blocked, 6 trapped in vehicles.',
    location_text: 'F-7 Markaz, College Road',
    city: 'Islamabad',
    latitude: 33.7215,
    longitude: 73.0560,
    affected_people_count: 6,
    priority: 'critical',
    priority_score: 91,
    status: 'en_route',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: false,
    synthetic_demo: true,
    assigned_resource_id: 'res-resp-1',
    assigned_resource_name: 'Rescue Squad R-01',
    vulnerabilities: { infants_count: 0, children_count: 0, elderly_count: 1, disabled_count: 0, pregnant_count: 0, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1049',
    incident_code: 'RG-1049',
    reporter_name: 'Maryam Akram',
    incident_type: 'road_accident',
    title: 'Multi-Vehicle Collision on Foggy Ring Road',
    description: 'Intercity bus and two vans collided due to zero visibility. Multiple entrapped passengers.',
    location_text: 'Lahore Ring Road near Band Road Interchange',
    city: 'Lahore',
    latitude: 31.5950,
    longitude: 74.3120,
    affected_people_count: 16,
    priority: 'critical',
    priority_score: 95,
    status: 'on_scene',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    assigned_resource_id: 'res-amb-1',
    assigned_resource_name: 'Emergency Ambulance Unit A-01',
    vulnerabilities: { infants_count: 0, children_count: 2, elderly_count: 3, disabled_count: 0, pregnant_count: 0, critical_medical_count: 5 },
    created_at: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1050',
    incident_code: 'RG-1050',
    reporter_name: 'Asad Cheema',
    incident_type: 'food_shortage',
    title: 'Evacuee Cluster at Government Primary School Requesting Ration Kits',
    description: '45 evacuated families from riverbed overflow require dry rations, baby formula, and clean water.',
    location_text: 'Govt Boys High School, Bosan Road',
    city: 'Multan',
    latitude: 30.2240,
    longitude: 71.4910,
    affected_people_count: 180,
    priority: 'medium',
    priority_score: 65,
    status: 'resource_matching',
    verification_status: 'verified',
    immediate_danger: false,
    medical_need: false,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 15, children_count: 48, elderly_count: 22, disabled_count: 3, pregnant_count: 6, critical_medical_count: 1 },
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1051',
    incident_code: 'RG-1051',
    reporter_name: 'Hassan Raza',
    incident_type: 'flood',
    title: 'Basement Inundation at Pediatric Clinic',
    description: 'Stormwater backflow inundated clinic basement containing pharmaceutical backup generators.',
    location_text: 'Gulshan-e-Iqbal Block 13-D',
    city: 'Karachi',
    latitude: 24.9280,
    longitude: 67.0850,
    affected_people_count: 9,
    priority: 'high',
    priority_score: 84,
    status: 'dispatched',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 4, children_count: 3, elderly_count: 0, disabled_count: 0, pregnant_count: 0, critical_medical_count: 2 },
    created_at: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1052',
    incident_code: 'RG-1052',
    reporter_name: 'Nadia Parveen',
    incident_type: 'medical_emergency',
    title: 'Respiratory Distress Surge Near Industrial Exhaust Area',
    description: 'Spill incident resulted in chemical fumes; 7 residents experiencing acute bronchospasm.',
    location_text: 'Korangi Industrial Sector 7-A',
    city: 'Karachi',
    latitude: 24.8320,
    longitude: 67.1350,
    affected_people_count: 7,
    priority: 'high',
    priority_score: 83,
    status: 'en_route',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 1, children_count: 2, elderly_count: 1, disabled_count: 0, pregnant_count: 1, critical_medical_count: 3 },
    created_at: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1053',
    incident_code: 'RG-1053',
    reporter_name: 'Rashid Minhas',
    incident_type: 'displacement',
    title: '80 Persons Displaced from Eroded River Embankment',
    description: 'River Chenab scouring washed out 14 makeshift shelters. Need immediate shelter transfer & bedding.',
    location_text: 'Suraj Miani Road',
    city: 'Multan',
    latitude: 30.1750,
    longitude: 71.4120,
    affected_people_count: 80,
    priority: 'high',
    priority_score: 79,
    status: 'prioritized',
    verification_status: 'verified',
    immediate_danger: false,
    medical_need: false,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 8, children_count: 24, elderly_count: 10, disabled_count: 2, pregnant_count: 3, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1054',
    incident_code: 'RG-1054',
    reporter_name: 'Iqbal Masih',
    incident_type: 'building_collapse',
    title: 'Old Mud-Brick House Wall Collapse',
    description: 'Continuous monsoon rain caused boundary wall collapse on two adjacent rooms. 4 injured.',
    location_text: 'Chungi Amar Sidhu',
    city: 'Lahore',
    latitude: 31.4720,
    longitude: 74.3640,
    affected_people_count: 4,
    priority: 'high',
    priority_score: 81,
    status: 'on_scene',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 0, children_count: 1, elderly_count: 1, disabled_count: 0, pregnant_count: 0, critical_medical_count: 2 },
    created_at: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1055',
    incident_code: 'RG-1055',
    reporter_name: 'Shahid Afridi',
    incident_type: 'heatwave',
    title: 'Dehydration Outpost Overload at Bus Stand',
    description: 'Community hydration stall ran out of ORS packets. 25 elders exhibiting dizzy spells.',
    location_text: 'Badami Bagh Lorry Adda',
    city: 'Lahore',
    latitude: 31.5980,
    longitude: 74.3210,
    affected_people_count: 25,
    priority: 'medium',
    priority_score: 68,
    status: 'resource_matching',
    verification_status: 'verified',
    immediate_danger: false,
    medical_need: true,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 0, children_count: 0, elderly_count: 18, disabled_count: 2, pregnant_count: 0, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 110).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1056',
    incident_code: 'RG-1056',
    reporter_name: 'Mehwish Hayat',
    incident_type: 'medical_supply_shortage',
    title: 'Critical Insulin & Snake Antivenom Stockout at Rural Outpost',
    description: 'Flood cutoff prevented weekly delivery to basic health unit. 6 bite victims and 12 diabetics at risk.',
    location_text: 'Rural Health Center, Kahna Nau',
    city: 'Lahore',
    latitude: 31.3650,
    longitude: 74.3720,
    affected_people_count: 18,
    priority: 'high',
    priority_score: 86,
    status: 'response_planning',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 0, children_count: 2, elderly_count: 5, disabled_count: 1, pregnant_count: 0, critical_medical_count: 6 },
    created_at: new Date(Date.now() - 1000 * 60 * 160).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1057',
    incident_code: 'RG-1057',
    reporter_name: 'Tahir Shah',
    incident_type: 'flood',
    title: 'Underpass Submerged with Stalled Public Bus',
    description: 'Kalma Chowk underpass flooded up to 6 feet after cloudburst. 30 passengers evacuated to upper deck.',
    location_text: 'Kalma Chowk Underpass',
    city: 'Lahore',
    latitude: 31.5035,
    longitude: 74.3318,
    affected_people_count: 30,
    priority: 'critical',
    priority_score: 93,
    status: 'resolved',
    verification_status: 'verified',
    immediate_danger: false,
    medical_need: false,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 2, children_count: 5, elderly_count: 4, disabled_count: 1, pregnant_count: 1, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1058',
    incident_code: 'RG-1058',
    reporter_name: 'Salma Batool',
    incident_type: 'earthquake',
    title: 'Tremor Damage to Stairwell in Multi-Unit Tenement',
    description: '4.8 magnitude tremor caused cracking and debris blocking the primary egress stairwell.',
    location_text: 'Sector G-9/2, Street 34',
    city: 'Islamabad',
    latitude: 33.6890,
    longitude: 73.0280,
    affected_people_count: 14,
    priority: 'high',
    priority_score: 80,
    status: 'resolved',
    verification_status: 'verified',
    immediate_danger: false,
    medical_need: false,
    synthetic_demo: true,
    vulnerabilities: { infants_count: 1, children_count: 3, elderly_count: 2, disabled_count: 1, pregnant_count: 0, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

// 15+ Rescue Resources with exact capabilities, coordinates, and status
export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'res-boat-3',
    name: 'Rapid Flood Rescue Boat B-03',
    resource_type: 'boat',
    capability: 'Shallow-water motorized zodiac, 12-person payload, trained swiftwater rescue divers & infant carriers',
    status: 'available',
    capacity: 12,
    city: 'Lahore',
    latitude: 31.6050,
    longitude: 74.2950,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-boat-7',
    name: 'Backup High-Capacity Rescue Boat B-07',
    resource_type: 'boat',
    capability: 'Rigid inflatable hull, 16-person payload, searchlights & stretcher deck',
    status: 'available',
    capacity: 16,
    city: 'Lahore',
    latitude: 31.5890,
    longitude: 74.3100,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-team-17',
    name: 'Emergency Swiftwater Rescue Team R-17',
    resource_type: 'rescue_team',
    capability: 'Specialized 6-person flood extraction unit with high-angle ropes, trauma tech, and survival gear',
    status: 'available',
    capacity: 6,
    city: 'Lahore',
    latitude: 31.5920,
    longitude: 74.3010,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-med-4',
    name: 'Mobile Pediatric & Geriatric Medical Unit M-04',
    resource_type: 'medical_team',
    capability: 'On-scene triage, pediatric resuscitation, emergency oxygen, IV hypothermia warming units',
    status: 'available',
    capacity: 4,
    city: 'Lahore',
    latitude: 31.5750,
    longitude: 74.3120,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-amb-1',
    name: 'Critical Care Ambulance Unit A-01',
    resource_type: 'ambulance',
    capability: 'Advanced Life Support, cardiac monitor, portable ventilator, suction, trauma medications',
    status: 'on_mission',
    capacity: 2,
    city: 'Lahore',
    latitude: 31.5950,
    longitude: 74.3120,
    current_incident_id: 'inc-1049',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-amb-3',
    name: 'Advanced Life Support Ambulance ALS-03',
    resource_type: 'ambulance',
    capability: 'ALS equipment, heatstroke cooling packs, IV rehydration, pulse oximetry, 2 stretchers',
    status: 'on_mission',
    capacity: 2,
    city: 'Karachi',
    latitude: 24.8508,
    longitude: 67.0011,
    current_incident_id: 'inc-1045',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-amb-5',
    name: 'Emergency Patient Transport Ambulance A-05',
    resource_type: 'ambulance',
    capability: 'Basic Life Support, oxygen concentrator, wheelchair ramp, emergency kit',
    status: 'available',
    capacity: 3,
    city: 'Lahore',
    latitude: 31.5497,
    longitude: 74.3436,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-boat-2',
    name: 'Zodiac Rescue Boat B-02',
    resource_type: 'boat',
    capability: '10-person zodiac inflatable, rescue throwlines, life jackets, megaphone',
    status: 'en_route',
    capacity: 10,
    city: 'Rawalpindi',
    latitude: 33.6050,
    longitude: 73.0550,
    current_incident_id: 'inc-1044',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-usar-1',
    name: 'Heavy USAR Unit H-01',
    resource_type: 'rescue_vehicle',
    capability: 'Urban Search and Rescue hydraulic cutters, acoustic listening devices, pneumatic shoring beams',
    status: 'on_mission',
    capacity: 8,
    city: 'Rawalpindi',
    latitude: 33.5973,
    longitude: 73.0479,
    current_incident_id: 'inc-1043',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-fire-1',
    name: 'HazMat & Foam Tender F-01',
    resource_type: 'fire_truck',
    capability: '5000L chemical foam cannon, SCBA air refill bank, chemical neutralization absorbent',
    status: 'on_mission',
    capacity: 5,
    city: 'Karachi',
    latitude: 24.9125,
    longitude: 66.9950,
    current_incident_id: 'inc-1046',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-resp-1',
    name: 'Rescue Squad R-01',
    resource_type: 'rescue_team',
    capability: 'Electrical hazard gloves, chainsaws, floodlights, technical winches',
    status: 'en_route',
    capacity: 4,
    city: 'Islamabad',
    latitude: 33.7215,
    longitude: 73.0560,
    current_incident_id: 'inc-1048',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-trans-1',
    name: 'Heavy Evacuation Carrier T-01',
    resource_type: 'transport',
    capability: 'All-terrain 4x4 35-seat high-clearance truck for flood evacuation',
    status: 'available',
    capacity: 35,
    city: 'Multan',
    latitude: 30.1890,
    longitude: 71.4550,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-eq-1',
    name: 'High-Volume Dewatering Pump Trailer P-01',
    resource_type: 'equipment',
    capability: '12-inch 5000 GPM submersible dewatering pump with 400m discharge hose',
    status: 'available',
    capacity: 0,
    city: 'Lahore',
    latitude: 31.5204,
    longitude: 74.3587,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-amb-9',
    name: 'Multan Emergency Ambulance A-09',
    resource_type: 'ambulance',
    capability: 'Basic Life Support, trauma splints, IV solutions, oxygen',
    status: 'available',
    capacity: 2,
    city: 'Multan',
    latitude: 30.2010,
    longitude: 71.4720,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-team-5',
    name: 'Karachi Coastal Rescue Team C-05',
    resource_type: 'rescue_team',
    capability: 'Maritime rescue, jetski support, tidal evacuation protocols',
    status: 'available',
    capacity: 5,
    city: 'Karachi',
    latitude: 24.8100,
    longitude: 67.0300,
    last_updated: new Date().toISOString(),
  }
];

// 8+ Hospitals with real clinical capacity metrics
export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-mayo',
    name: 'Mayo Hospital Emergency & Trauma Complex',
    location: 'Hospital Road, Anarkali',
    city: 'Lahore',
    latitude: 31.5724,
    longitude: 74.3168,
    emergency_capacity: 120,
    available_beds: 34,
    icu_beds: 8,
    ventilators: 6,
    blood_units: 82,
    emergency_status: 'moderate_pressure',
    capabilities: ['trauma_level_1', 'pediatric_emergency', 'hyperbaric_oxygen', 'burns_unit', 'dialysis'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-jinnah-lhr',
    name: 'Jinnah Hospital Tertiary Trauma Center',
    location: 'Usman Block, Garden Town',
    city: 'Lahore',
    latitude: 31.4852,
    longitude: 74.3014,
    emergency_capacity: 90,
    available_beds: 22,
    icu_beds: 5,
    ventilators: 4,
    blood_units: 65,
    emergency_status: 'normal',
    capabilities: ['trauma_level_1', 'emergency_surgery', 'neonatal_icu', 'orthopedic_surgery'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-services-lhr',
    name: 'Services Institute of Medical Sciences',
    location: 'Jail Road',
    city: 'Lahore',
    latitude: 31.5412,
    longitude: 74.3340,
    emergency_capacity: 80,
    available_beds: 18,
    icu_beds: 4,
    ventilators: 3,
    blood_units: 54,
    emergency_status: 'normal',
    capabilities: ['emergency_internal_medicine', 'pediatrics', 'pulmonology'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-jpmc-khi',
    name: 'Jinnah Postgraduate Medical Centre (JPMC)',
    location: 'Rafiqui Shaheed Road, Cantonment',
    city: 'Karachi',
    latitude: 24.8528,
    longitude: 67.0456,
    emergency_capacity: 150,
    available_beds: 28,
    icu_beds: 6,
    ventilators: 5,
    blood_units: 95,
    emergency_status: 'high_pressure',
    capabilities: ['trauma_level_1', 'heatstroke_center', 'toxicology', 'neurosurgery'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-civil-khi',
    name: 'Dr. Ruth K.M. Pfau Civil Hospital',
    location: 'Mission Road',
    city: 'Karachi',
    latitude: 24.8590,
    longitude: 67.0105,
    emergency_capacity: 110,
    available_beds: 19,
    icu_beds: 3,
    ventilators: 4,
    blood_units: 70,
    emergency_status: 'moderate_pressure',
    capabilities: ['emergency_triage', 'infectious_diseases', 'burn_center'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-pims-isb',
    name: 'Pakistan Institute of Medical Sciences (PIMS)',
    location: 'Sector G-8/3',
    city: 'Islamabad',
    latitude: 33.7056,
    longitude: 73.0520,
    emergency_capacity: 100,
    available_beds: 41,
    icu_beds: 9,
    ventilators: 7,
    blood_units: 110,
    emergency_status: 'normal',
    capabilities: ['trauma_level_1', 'cardiac_emergency', 'maternal_fetal_medicine'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-holy-rwp',
    name: 'Holy Family Hospital',
    location: 'Murree Road, Satellite Town',
    city: 'Rawalpindi',
    latitude: 33.6335,
    longitude: 73.0720,
    emergency_capacity: 85,
    available_beds: 15,
    icu_beds: 2,
    ventilators: 3,
    blood_units: 48,
    emergency_status: 'high_pressure',
    capabilities: ['flood_casualty_reception', 'orthopedics', 'pediatrics'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-nishtar-mul',
    name: 'Nishtar Hospital & Trauma Center',
    location: 'Nishtar Road',
    city: 'Multan',
    latitude: 30.1884,
    longitude: 71.4428,
    emergency_capacity: 95,
    available_beds: 26,
    icu_beds: 5,
    ventilators: 4,
    blood_units: 58,
    emergency_status: 'moderate_pressure',
    capabilities: ['snakebite_treatment', 'trauma_care', 'emergency_surgery'],
    updated_at: new Date().toISOString(),
  }
];

// 10+ Shelters with capacity and vulnerable facility tags
export const INITIAL_SHELTERS: Shelter[] = [
  {
    id: 'shelter-expo-lhr',
    name: 'Expo Center Emergency Relief & Evacuation Shelter S-12',
    location: 'Trade Centre, Abdul Haque Rd, Johar Town',
    city: 'Lahore',
    latitude: 31.4680,
    longitude: 74.2750,
    total_capacity: 450,
    current_occupancy: 120,
    food_hours_remaining: 120,
    water_hours_remaining: 96,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-shahdara-lhr',
    name: 'Govt Degree College Community Shelter',
    location: 'Old GT Road, Shahdara',
    city: 'Lahore',
    latitude: 31.6250,
    longitude: 74.2880,
    total_capacity: 250,
    current_occupancy: 210,
    food_hours_remaining: 36,
    water_hours_remaining: 24,
    medical_support: true,
    accessibility_support: false,
    family_area: true,
    children_area: false,
    status: 'near_capacity',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-alhamra-lhr',
    name: 'Alhamra Relief Center',
    location: '68 Mall Road',
    city: 'Lahore',
    latitude: 31.5580,
    longitude: 74.3310,
    total_capacity: 300,
    current_occupancy: 95,
    food_hours_remaining: 72,
    water_hours_remaining: 60,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-sports-isb',
    name: 'Pakistan Sports Complex Indoor Shelter',
    location: 'Kashmir Highway, Sector G-6',
    city: 'Islamabad',
    latitude: 33.7020,
    longitude: 73.0980,
    total_capacity: 600,
    current_occupancy: 180,
    food_hours_remaining: 144,
    water_hours_remaining: 120,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-liaquat-rwp',
    name: 'Liaquat Memorial Hall Emergency Camp',
    location: 'Liaquat Bagh, Murree Road',
    city: 'Rawalpindi',
    latitude: 33.6060,
    longitude: 73.0670,
    total_capacity: 350,
    current_occupancy: 315,
    food_hours_remaining: 28,
    water_hours_remaining: 18,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: false,
    status: 'near_capacity',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-kpt-khi',
    name: 'KPT Sports Complex Coastal Evacuation Hub',
    location: 'Mai Kolachi Bypass',
    city: 'Karachi',
    latitude: 24.8350,
    longitude: 66.9920,
    total_capacity: 500,
    current_occupancy: 175,
    food_hours_remaining: 90,
    water_hours_remaining: 72,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-gulberg-khi',
    name: 'Community Center FB Area',
    location: 'Block 16, Federal B Area',
    city: 'Karachi',
    latitude: 24.9380,
    longitude: 67.0680,
    total_capacity: 220,
    current_occupancy: 80,
    food_hours_remaining: 60,
    water_hours_remaining: 48,
    medical_support: false,
    accessibility_support: false,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-qasim-mul',
    name: 'Qasim Fort Public Relief Camp',
    location: 'Fort Kohna Qasim Garden',
    city: 'Multan',
    latitude: 30.1980,
    longitude: 71.4720,
    total_capacity: 400,
    current_occupancy: 280,
    food_hours_remaining: 48,
    water_hours_remaining: 36,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-bosan-mul',
    name: 'Bosan Road Model School Shelter',
    location: 'Bosan Road',
    city: 'Multan',
    latitude: 30.2310,
    longitude: 71.4980,
    total_capacity: 200,
    current_occupancy: 190,
    food_hours_remaining: 24,
    water_hours_remaining: 16,
    medical_support: false,
    accessibility_support: true,
    family_area: true,
    children_area: false,
    status: 'near_capacity',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-fatima-lhr',
    name: 'Fatima Jinnah Hall Emergency Shelter',
    location: 'Queens Road',
    city: 'Lahore',
    latitude: 31.5510,
    longitude: 74.3200,
    total_capacity: 280,
    current_occupancy: 110,
    food_hours_remaining: 84,
    water_hours_remaining: 70,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  }
];

// 5+ Relief Hubs
export const INITIAL_RELIEF_HUBS: ReliefHub[] = [
  {
    id: 'hub-lhr-central',
    name: 'Lahore Central Humanitarian Logistics Depot',
    location: 'Multan Road near Thokar Niaz Baig',
    city: 'Lahore',
    latitude: 31.4680,
    longitude: 74.2380,
    status: 'operational',
    created_at: new Date().toISOString(),
  },
  {
    id: 'hub-khi-port',
    name: 'Karachi Port Trust Emergency Warehouse',
    location: 'West Wharf',
    city: 'Karachi',
    latitude: 24.8420,
    longitude: 66.9740,
    status: 'operational',
    created_at: new Date().toISOString(),
  },
  {
    id: 'hub-isb-ndma',
    name: 'National Disaster Preparedness Hub H-9',
    location: 'Sector H-9/1',
    city: 'Islamabad',
    latitude: 33.6780,
    longitude: 73.0450,
    status: 'operational',
    created_at: new Date().toISOString(),
  },
  {
    id: 'hub-rwp-cantt',
    name: 'Rawalpindi Civil Defense Logistics Reserve',
    location: 'The Mall, Cantt',
    city: 'Rawalpindi',
    latitude: 33.5910,
    longitude: 73.0490,
    status: 'operational',
    created_at: new Date().toISOString(),
  },
  {
    id: 'hub-mul-bypass',
    name: 'South Punjab Regional Relief Cache',
    location: 'Northern Bypass Interchange',
    city: 'Multan',
    latitude: 30.2450,
    longitude: 71.4880,
    status: 'operational',
    created_at: new Date().toISOString(),
  }
];

// Relief Inventory
export const INITIAL_INVENTORY: ReliefItem[] = [
  { id: 'inv-1', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'drinking_water', quantity: 24000, unit: 'liters', minimum_threshold: 5000, updated_at: new Date().toISOString() },
  { id: 'inv-2', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'food_packages', quantity: 3800, unit: 'family packs', minimum_threshold: 1000, updated_at: new Date().toISOString() },
  { id: 'inv-3', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'medicines', quantity: 1500, unit: 'first aid & cholera kits', minimum_threshold: 300, updated_at: new Date().toISOString() },
  { id: 'inv-4', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'baby_supplies', quantity: 850, unit: 'formula & diaper packs', minimum_threshold: 200, updated_at: new Date().toISOString() },
  { id: 'inv-5', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'blankets', quantity: 4200, unit: 'thermal blankets', minimum_threshold: 800, updated_at: new Date().toISOString() },
  { id: 'inv-6', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'tents', quantity: 650, unit: 'weatherproof family tents', minimum_threshold: 150, updated_at: new Date().toISOString() },
  { id: 'inv-7', hub_id: 'hub-khi-port', hub_name: 'Karachi Port Hub', resource_category: 'drinking_water', quantity: 45000, unit: 'liters', minimum_threshold: 10000, updated_at: new Date().toISOString() },
  { id: 'inv-8', hub_id: 'hub-khi-port', hub_name: 'Karachi Port Hub', resource_category: 'generators', quantity: 45, unit: 'diesel 5kW units', minimum_threshold: 10, updated_at: new Date().toISOString() },
  { id: 'inv-9', hub_id: 'hub-isb-ndma', hub_name: 'NDMA Hub H-9', resource_category: 'emergency_equipment', quantity: 120, unit: 'inflatable rescue kits', minimum_threshold: 25, updated_at: new Date().toISOString() },
  { id: 'inv-10', hub_id: 'hub-rwp-cantt', hub_name: 'Rawalpindi Reserve', resource_category: 'hygiene_kits', quantity: 2100, unit: 'sanitation packs', minimum_threshold: 500, updated_at: new Date().toISOString() }
];

// 20+ Volunteers
export const INITIAL_VOLUNTEERS: Volunteer[] = [
  { id: 'vol-1', name: 'Dr. Ayesha Siddiqui', email: 'ayesha.s@example.org', phone: '+92 300 1112233', city: 'Lahore', skills: ['Emergency Medicine', 'Pediatrics', 'Triage'], languages: ['English', 'Urdu', 'Punjabi'], availability_status: 'available', verification_status: 'verified', latitude: 31.5204, longitude: 74.3587, hours_contributed: 64, created_at: new Date().toISOString() },
  { id: 'vol-2', name: 'Hamza Farooq', email: 'hamza.f@example.org', phone: '+92 321 4445566', city: 'Lahore', skills: ['Heavy Driving', 'Boat Handling', 'Logistics'], languages: ['English', 'Urdu'], availability_status: 'available', verification_status: 'verified', latitude: 31.5540, longitude: 74.3120, hours_contributed: 42, created_at: new Date().toISOString() },
  { id: 'vol-3', name: 'Zeeshan Malik', email: 'zeeshan.m@example.org', phone: '+92 333 7778899', city: 'Rawalpindi', skills: ['Search and Rescue', 'First Aid', 'Radio Operator'], languages: ['Urdu', 'Potohari', 'English'], availability_status: 'available', verification_status: 'verified', latitude: 33.6000, longitude: 73.0500, hours_contributed: 55, created_at: new Date().toISOString() },
  { id: 'vol-4', name: 'Sanaullah Khan', email: 'sana.k@example.org', phone: '+92 345 9990011', city: 'Karachi', skills: ['Water Rescue', 'Crowd Management', 'Food Distribution'], languages: ['Urdu', 'Sindhi', 'Balochi'], availability_status: 'available', verification_status: 'verified', latitude: 24.8600, longitude: 67.0100, hours_contributed: 38, created_at: new Date().toISOString() },
  { id: 'vol-5', name: 'Mariam Nawazish', email: 'mariam.n@example.org', phone: '+92 301 2223344', city: 'Islamabad', skills: ['Child Care', 'Psychological First Aid', 'Translation'], languages: ['English', 'Urdu', 'Pashto'], availability_status: 'available', verification_status: 'verified', latitude: 33.7100, longitude: 73.0600, hours_contributed: 29, created_at: new Date().toISOString() },
  { id: 'vol-6', name: 'Noman Bashir', email: 'noman.b@example.org', phone: '+92 312 6667788', city: 'Multan', skills: ['Warehouse Operations', 'Data Entry', 'Forklift'], languages: ['Urdu', 'Saraiki'], availability_status: 'available', verification_status: 'verified', latitude: 30.2000, longitude: 71.4600, hours_contributed: 49, created_at: new Date().toISOString() },
];

// Safety Alerts
export const INITIAL_ALERTS: SafetyAlert[] = [
  {
    id: 'alert-1',
    title: 'RED ALERT: Extreme River Ravi Overflow Warning',
    description: 'Upstream barrage water discharge exceeding 85,000 cusecs. Residents within 1.5km of Shahdara basin are advised to evacuate to higher ground.',
    alert_type: 'flood_warning',
    severity: 'critical',
    location: 'Ravi Riverbank & Shahdara Town',
    city: 'Lahore',
    active_from: new Date().toISOString(),
    active_until: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    synthetic_demo: true,
  },
  {
    id: 'alert-2',
    title: 'Nullah Lai Torrential Flash Flood Advisory',
    description: 'Water level reached 19.5 feet at Katarian Bridge. Siren warning Level 2 initiated for low-lying wards.',
    alert_type: 'flood_warning',
    severity: 'severe',
    location: 'Nullah Lai Corridor',
    city: 'Rawalpindi',
    active_from: new Date().toISOString(),
    active_until: new Date(Date.now() + 1000 * 60 * 60 * 18).toISOString(),
    synthetic_demo: true,
  },
  {
    id: 'alert-3',
    title: 'Severe Heatwave Advisory — Code Orange',
    description: 'Heat index reaching 51°C. 18 community misting hydration points operational.',
    alert_type: 'heatwave_advisory',
    severity: 'moderate',
    location: 'District South & Central',
    city: 'Karachi',
    active_from: new Date().toISOString(),
    active_until: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    synthetic_demo: true,
  }
];

// Demo recommendation for the primary incident
export const PRIMARY_DEMO_RECOMMENDATION: AIRecommendation = {
  id: 'rec-demo-1042',
  incident_id: 'inc-demo-primary',
  recommendation_type: 'emergency_dispatch_and_routing',
  recommendation: 'Dispatch Rapid Flood Rescue Boat B-03 + Emergency Team R-17; Pre-alert Mayo Hospital Trauma Complex; Assign Expo Center Shelter S-12.',
  recommended_resources: [
    { resource_id: 'res-boat-3', resource_name: 'Rapid Flood Rescue Boat B-03', resource_type: 'boat', role: 'Primary Extraction Vessel' },
    { resource_id: 'res-team-17', resource_name: 'Emergency Swiftwater Rescue Team R-17', resource_type: 'rescue_team', role: 'Specialized Swiftwater Extraction' },
    { resource_id: 'res-med-4', resource_name: 'Mobile Pediatric & Geriatric Unit M-04', resource_type: 'medical_team', role: 'On-scene hypothermia & oxygen stabilization' }
  ],
  recommended_hospital: {
    hospital_id: 'hosp-mayo',
    hospital_name: 'Mayo Hospital Emergency & Trauma Complex',
    reason: 'Nearest Level-1 facility (4.2km) with pediatric ICU and emergency geriatric beds available.'
  },
  recommended_shelter: {
    shelter_id: 'shelter-expo-lhr',
    shelter_name: 'Expo Center Emergency Shelter S-12',
    reason: 'Capacity for 330 additional evacuees, dedicated infant supplies and family rooms.'
  },
  reasoning: {
    factors: [
      '18 people affected (above high-capacity threshold)',
      '1 infant (high risk of cold exposure / hypothermia)',
      '2 elderly people (mobility limitations & oxygen dependency)',
      'Active water level rising > 4.5 feet requires motorized boat extraction',
      'Boat B-03 stationed 3.1 km away with 12-person payload capacity'
    ],
    affected_breakdown: '18 Total: 1 Infant, 3 Children, 2 Elderly, 1 Disabled, 11 Adults',
    urgency_rationale: 'Rising flood waters cut off road access. Immediate water-borne rescue required within 20 minutes.',
    data_points_used: [
      'Shahdara flood gauge telemetry: +0.4 ft/hr',
      'Resource proximity matrix: B-03 ETA 11 mins',
      'Mayo Hospital: 34 beds available, 6 ventilators',
      'Shelter S-12: 120h food, 96h water remaining'
    ]
  },
  confidence: 94.6,
  status: 'pending',
  created_at: new Date().toISOString(),
};
