import {
  Incident,
  Resource,
  Hospital,
  Shelter,
  ReliefHub,
  ReliefItem,
  Volunteer,
  SafetyAlert,
  AIRecommendation,
  EmergencyZone,
} from '../types';

export const INITIAL_ZONES: EmergencyZone[] = [
  { id: 'zone-1', name: 'Zone 4 — Ravi Basin Floodway', city: 'Lahore', risk_level: 'critical', population_estimate: 85000, synthetic_demo: true, active_incidents_count: 7 },
  { id: 'zone-2', name: 'Lyari Coastal Sector 2', city: 'Karachi', risk_level: 'high', population_estimate: 140000, synthetic_demo: true, active_incidents_count: 5 },
  { id: 'zone-3', name: 'Margalla Foothills Sector E-11', city: 'Islamabad', risk_level: 'moderate', population_estimate: 42000, synthetic_demo: true, active_incidents_count: 3 },
  { id: 'zone-4', name: 'Nullah Lai Corridor', city: 'Rawalpindi', risk_level: 'critical', population_estimate: 110000, synthetic_demo: true, active_incidents_count: 6 },
  { id: 'zone-5', name: 'Chenab Flood Embankment', city: 'Multan', risk_level: 'high', population_estimate: 65000, synthetic_demo: true, active_incidents_count: 4 },
];

export const PRIMARY_DEMO_INCIDENT: Incident = {
  id: 'inc-demo-primary',
  incident_code: 'RG-1042',
  reporter_id: 'user-citizen-1',
  reporter_name: 'Tariq Mehmood',
  reporter_phone: '+92 300 5551042',
  incident_type: 'flood',
  title: '18 People Trapped in Rapidly Flooding Residential Street',
  description: '18 people are trapped in a flooded neighborhood. Two elderly people and one infant need assistance. Water level rising above 4.5 feet. Medical support may be required immediately.',
  location_text: 'Street 7, Sector B, Shahdara Town near Ravi Riverbank',
  city: 'Lahore',
  latitude: 31.6210,
  longitude: 74.2825,
  affected_people_count: 18,
  priority: 'critical',
  priority_score: 96,
  status: 'awaiting_approval',
  verification_status: 'verified',
  immediate_danger: true,
  medical_need: true,
  synthetic_demo: true,
  vulnerabilities: {
    infants_count: 1,
    children_count: 3,
    elderly_count: 2,
    disabled_count: 1,
    pregnant_count: 0,
    critical_medical_count: 1,
    notes: 'Elderly diabetic female requiring oxygen assistance, 7-month infant in cold water exposure risk.'
  },
  created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  updated_at: new Date().toISOString(),
};

export const INITIAL_INCIDENTS: Incident[] = [
  PRIMARY_DEMO_INCIDENT,
  {
    id: 'inc-1043',
    incident_code: 'RG-1043',
    reporter_name: 'Fatima Zahra',
    incident_type: 'building_collapse',
    title: 'Partial Roof Collapse at 3-Story Commercial Plaza',
    description: 'Ground floor structural column yielded following heavy downpour. 8 people trapped inside store.',
    location_text: 'Bismillah Chowk, Saddar Bazaar',
    city: 'Rawalpindi',
    latitude: 33.5973,
    longitude: 73.0479,
    affected_people_count: 8,
    priority: 'critical',
    priority_score: 92,
    status: 'dispatched',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    assigned_resource_id: 'res-usar-1',
    assigned_resource_name: 'Heavy USAR Unit H-01',
    vulnerabilities: { infants_count: 0, children_count: 1, elderly_count: 2, disabled_count: 0, pregnant_count: 0, critical_medical_count: 2 },
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1044',
    incident_code: 'RG-1044',
    reporter_name: 'Bilal Khan',
    incident_type: 'flood',
    title: 'Flash Flood Cutoff in Low-Lying Settlement',
    description: 'Nullah Lai water overflowed boundary wall. 12 residents stranded on rooftop.',
    location_text: 'Dhok Ratta, near Railway Bridge',
    city: 'Rawalpindi',
    latitude: 33.6050,
    longitude: 73.0550,
    affected_people_count: 12,
    priority: 'critical',
    priority_score: 89,
    status: 'en_route',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: false,
    synthetic_demo: true,
    assigned_resource_id: 'res-boat-2',
    assigned_resource_name: 'Zodiac Rescue Boat B-02',
    vulnerabilities: { infants_count: 1, children_count: 4, elderly_count: 1, disabled_count: 0, pregnant_count: 1, critical_medical_count: 0 },
    created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inc-1045',
    incident_code: 'RG-1045',
    reporter_name: 'Dr. Kamran Qureshi',
    incident_type: 'heatwave',
    title: 'Severe Heat Exhaustion Cluster at Transit Terminal',
    description: '14 commuters collapsed due to 46°C temperature with high humidity. Need mobile cooling & IV fluids.',
    location_text: 'Tower Bus Interchange, I.I. Chundrigar Road',
    city: 'Karachi',
    latitude: 24.8508,
    longitude: 67.0011,
    affected_people_count: 14,
    priority: 'high',
    priority_score: 82,
    status: 'on_scene',
    verification_status: 'verified',
    immediate_danger: true,
    medical_need: true,
    synthetic_demo: true,
    assigned_resource_id: 'res-amb-3',
    assigned_resource_name: 'Advanced Life Support Ambulance ALS-03',
    vulnerabilities: { infants_count: 0, children_count: 0, elderly_count: 4, disabled_count: 1, pregnant_count: 0, critical_medical_count: 3 },
    created_at: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_RESOURCES: Resource[] = [
  {
    id: 'res-boat-3',
    name: 'Rapid Flood Rescue Boat B-03',
    resource_type: 'boat',
    capability: 'Shallow-water motorized zodiac, 12-person payload, trained swiftwater rescue divers & infant carriers',
    status: 'available',
    capacity: 12,
    city: 'Lahore',
    latitude: 31.6050,
    longitude: 74.2950,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-boat-7',
    name: 'Backup High-Capacity Rescue Boat B-07',
    resource_type: 'boat',
    capability: 'Rigid inflatable hull, 16-person payload, searchlights & stretcher deck',
    status: 'available',
    capacity: 16,
    city: 'Lahore',
    latitude: 31.5890,
    longitude: 74.3100,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-team-17',
    name: 'Emergency Swiftwater Rescue Team R-17',
    resource_type: 'rescue_team',
    capability: 'Specialized 6-person flood extraction unit with high-angle ropes, trauma tech, and survival gear',
    status: 'available',
    capacity: 6,
    city: 'Lahore',
    latitude: 31.5920,
    longitude: 74.3010,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-med-4',
    name: 'Mobile Pediatric & Geriatric Medical Unit M-04',
    resource_type: 'medical_team',
    capability: 'On-scene triage, pediatric resuscitation, emergency oxygen, IV hypothermia warming units',
    status: 'available',
    capacity: 4,
    city: 'Lahore',
    latitude: 31.5750,
    longitude: 74.3120,
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-amb-1',
    name: 'Critical Care Ambulance Unit A-01',
    resource_type: 'ambulance',
    capability: 'Advanced Life Support, cardiac monitor, portable ventilator, suction, trauma medications',
    status: 'on_mission',
    capacity: 2,
    city: 'Lahore',
    latitude: 31.5950,
    longitude: 74.3120,
    current_incident_id: 'inc-1049',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-amb-3',
    name: 'Advanced Life Support Ambulance ALS-03',
    resource_type: 'ambulance',
    capability: 'ALS equipment, heatstroke cooling packs, IV rehydration, pulse oximetry, 2 stretchers',
    status: 'on_mission',
    capacity: 2,
    city: 'Karachi',
    latitude: 24.8508,
    longitude: 67.0011,
    current_incident_id: 'inc-1045',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-boat-2',
    name: 'Zodiac Rescue Boat B-02',
    resource_type: 'boat',
    capability: '10-person zodiac inflatable, rescue throwlines, life jackets, megaphone',
    status: 'en_route',
    capacity: 10,
    city: 'Rawalpindi',
    latitude: 33.6050,
    longitude: 73.0550,
    current_incident_id: 'inc-1044',
    last_updated: new Date().toISOString(),
  },
  {
    id: 'res-usar-1',
    name: 'Heavy USAR Unit H-01',
    resource_type: 'rescue_vehicle',
    capability: 'Urban Search and Rescue hydraulic cutters, acoustic listening devices, pneumatic shoring beams',
    status: 'on_mission',
    capacity: 8,
    city: 'Rawalpindi',
    latitude: 33.5973,
    longitude: 73.0479,
    current_incident_id: 'inc-1043',
    last_updated: new Date().toISOString(),
  }
];

export const INITIAL_HOSPITALS: Hospital[] = [
  {
    id: 'hosp-mayo',
    name: 'Mayo Hospital Emergency & Trauma Complex',
    location: 'Hospital Road, Anarkali',
    city: 'Lahore',
    latitude: 31.5724,
    longitude: 74.3168,
    emergency_capacity: 120,
    available_beds: 34,
    icu_beds: 8,
    ventilators: 6,
    blood_units: 82,
    emergency_status: 'moderate_pressure',
    capabilities: ['trauma_level_1', 'pediatric_emergency', 'hyperbaric_oxygen', 'burns_unit', 'dialysis'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-jinnah-lhr',
    name: 'Jinnah Hospital Tertiary Trauma Center',
    location: 'Usman Block, Garden Town',
    city: 'Lahore',
    latitude: 31.4852,
    longitude: 74.3014,
    emergency_capacity: 90,
    available_beds: 22,
    icu_beds: 5,
    ventilators: 4,
    blood_units: 65,
    emergency_status: 'normal',
    capabilities: ['trauma_level_1', 'emergency_surgery', 'neonatal_icu', 'orthopedic_surgery'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-jpmc-khi',
    name: 'Jinnah Postgraduate Medical Centre (JPMC)',
    location: 'Rafiqui Shaheed Road, Cantonment',
    city: 'Karachi',
    latitude: 24.8528,
    longitude: 67.0456,
    emergency_capacity: 150,
    available_beds: 28,
    icu_beds: 6,
    ventilators: 5,
    blood_units: 95,
    emergency_status: 'high_pressure',
    capabilities: ['trauma_level_1', 'heatstroke_center', 'toxicology', 'neurosurgery'],
    updated_at: new Date().toISOString(),
  },
  {
    id: 'hosp-pims-isb',
    name: 'Pakistan Institute of Medical Sciences (PIMS)',
    location: 'Sector G-8/3',
    city: 'Islamabad',
    latitude: 33.7056,
    longitude: 73.0520,
    emergency_capacity: 100,
    available_beds: 41,
    icu_beds: 9,
    ventilators: 7,
    blood_units: 110,
    emergency_status: 'normal',
    capabilities: ['trauma_level_1', 'cardiac_emergency', 'maternal_fetal_medicine'],
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_SHELTERS: Shelter[] = [
  {
    id: 'shelter-expo-lhr',
    name: 'Expo Center Emergency Relief & Evacuation Shelter S-12',
    location: 'Trade Centre, Abdul Haque Rd, Johar Town',
    city: 'Lahore',
    latitude: 31.4680,
    longitude: 74.2750,
    total_capacity: 450,
    current_occupancy: 120,
    food_hours_remaining: 120,
    water_hours_remaining: 96,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-shahdara-lhr',
    name: 'Govt Degree College Community Shelter',
    location: 'Old GT Road, Shahdara',
    city: 'Lahore',
    latitude: 31.6250,
    longitude: 74.2880,
    total_capacity: 250,
    current_occupancy: 210,
    food_hours_remaining: 36,
    water_hours_remaining: 24,
    medical_support: true,
    accessibility_support: false,
    family_area: true,
    children_area: false,
    status: 'near_capacity',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'shelter-sports-isb',
    name: 'Pakistan Sports Complex Indoor Shelter',
    location: 'Kashmir Highway, Sector G-6',
    city: 'Islamabad',
    latitude: 33.7020,
    longitude: 73.0980,
    total_capacity: 600,
    current_occupancy: 180,
    food_hours_remaining: 144,
    water_hours_remaining: 120,
    medical_support: true,
    accessibility_support: true,
    family_area: true,
    children_area: true,
    status: 'open',
    updated_at: new Date().toISOString(),
  }
];

export const INITIAL_RELIEF_HUBS: ReliefHub[] = [
  {
    id: 'hub-lhr-central',
    name: 'Lahore Central Humanitarian Logistics Depot',
    location: 'Multan Road near Thokar Niaz Baig',
    city: 'Lahore',
    latitude: 31.4680,
    longitude: 74.2380,
    status: 'operational',
    created_at: new Date().toISOString(),
  },
  {
    id: 'hub-khi-port',
    name: 'Karachi Port Trust Emergency Warehouse',
    location: 'West Wharf',
    city: 'Karachi',
    latitude: 24.8420,
    longitude: 66.9740,
    status: 'operational',
    created_at: new Date().toISOString(),
  }
];

export const INITIAL_INVENTORY: ReliefItem[] = [
  { id: 'inv-1', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'drinking_water', quantity: 24000, unit: 'liters', minimum_threshold: 5000, updated_at: new Date().toISOString() },
  { id: 'inv-2', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'food_packages', quantity: 3800, unit: 'family packs', minimum_threshold: 1000, updated_at: new Date().toISOString() },
  { id: 'inv-3', hub_id: 'hub-lhr-central', hub_name: 'Lahore Central Depot', resource_category: 'medicines', quantity: 1500, unit: 'first aid & cholera kits', minimum_threshold: 300, updated_at: new Date().toISOString() }
];

export const INITIAL_VOLUNTEERS: Volunteer[] = [
  { id: 'vol-1', name: 'Dr. Ayesha Siddiqui', email: 'ayesha.s@example.org', phone: '+92 300 1112233', city: 'Lahore', skills: ['Emergency Medicine', 'Pediatrics', 'Triage'], languages: ['English', 'Urdu', 'Punjabi'], availability_status: 'available', verification_status: 'verified', latitude: 31.5204, longitude: 74.3587, hours_contributed: 64, created_at: new Date().toISOString() },
  { id: 'vol-2', name: 'Hamza Farooq', email: 'hamza.f@example.org', phone: '+92 321 4445566', city: 'Lahore', skills: ['Heavy Driving', 'Boat Handling', 'Logistics'], languages: ['English', 'Urdu'], availability_status: 'available', verification_status: 'verified', latitude: 31.5540, longitude: 74.3120, hours_contributed: 42, created_at: new Date().toISOString() }
];

export const INITIAL_ALERTS: SafetyAlert[] = [
  {
    id: 'alert-1',
    title: 'RED ALERT: Extreme River Ravi Overflow Warning',
    description: 'Upstream barrage water discharge exceeding 85,000 cusecs. Residents within 1.5km of Shahdara basin are advised to evacuate to higher ground.',
    alert_type: 'flood_warning',
    severity: 'critical',
    location: 'Ravi Riverbank & Shahdara Town',
    city: 'Lahore',
    active_from: new Date().toISOString(),
    active_until: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    synthetic_demo: true,
  }
];

export const PRIMARY_DEMO_RECOMMENDATION: AIRecommendation = {
  id: 'rec-demo-1042',
  incident_id: 'inc-demo-primary',
  recommendation_type: 'emergency_dispatch_and_routing',
  recommendation: 'Dispatch Rapid Flood Rescue Boat B-03 + Emergency Team R-17; Pre-alert Mayo Hospital Trauma Complex; Assign Expo Center Shelter S-12.',
  recommended_resources: [
    { resource_id: 'res-boat-3', resource_name: 'Rapid Flood Rescue Boat B-03', resource_type: 'boat', role: 'Primary Extraction Vessel' },
    { resource_id: 'res-team-17', resource_name: 'Emergency Swiftwater Rescue Team R-17', resource_type: 'rescue_team', role: 'Specialized Swiftwater Extraction' },
    { resource_id: 'res-med-4', resource_name: 'Mobile Pediatric & Geriatric Unit M-04', resource_type: 'medical_team', role: 'On-scene hypothermia & oxygen stabilization' }
  ],
  recommended_hospital: {
    hospital_id: 'hosp-mayo',
    hospital_name: 'Mayo Hospital Emergency & Trauma Complex',
    reason: 'Nearest Level-1 facility (4.2km) with pediatric ICU and emergency geriatric beds available.'
  },
  recommended_shelter: {
    shelter_id: 'shelter-expo-lhr',
    shelter_name: 'Expo Center Emergency Shelter S-12',
    reason: 'Capacity for 330 additional evacuees, dedicated infant supplies and family rooms.'
  },
  reasoning: {
    factors: [
      '18 people affected (above high-capacity threshold)',
      '1 infant (high risk of cold exposure / hypothermia)',
      '2 elderly people (mobility limitations & oxygen dependency)',
      'Active water level rising > 4.5 feet requires motorized boat extraction',
      'Boat B-03 stationed 3.1 km away with 12-person payload capacity'
    ],
    affected_breakdown: '18 Total: 1 Infant, 3 Children, 2 Elderly, 1 Disabled, 11 Adults',
    urgency_rationale: 'Rising flood waters cut off road access. Immediate water-borne rescue required within 20 minutes.',
    data_points_used: [
      'Shahdara flood gauge telemetry: +0.4 ft/hr',
      'Resource proximity matrix: B-03 ETA 11 mins',
      'Mayo Hospital: 34 beds available, 6 ventilators',
      'Shelter S-12: 120h food, 96h water remaining'
    ]
  },
  confidence: 94.6,
  status: 'pending',
  created_at: new Date().toISOString(),
};
